# spring boot端口配置
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sovpft
    username: root
    password: 123456

  # Thymeleaf模板的配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**